### ISSUE TITLE
Incorrect Labeling of DataTrack

### ISSUE THREAD

**Issue by drneavin** [ivanek/Gviz#10]
Hi there,

I am new to gviz and love the ease of using this package to plot different types of genomic data together. However, I have recently tried to make a DataTrack and found that the points were mislabeled after plotting and don't match the labeling in the rownames(DataTrack@data).

Here is an example to demonstrate the issue. This is the dTrack@metadata so you can see that there should be points for beta_iPSC_Cluster3 and beta_fibroblast_Cluster3
![image](https://user-images.githubusercontent.com/44268007/65111034-c7a69280-da1d-11e9-9354-c504ccccc426.png)

But when I plot them, they are labeled as beta_iPSC_Cluster3 and **beta_fibroblast_Cluster5**

![dTrackPlot](https://user-images.githubusercontent.com/44268007/65111132-2704a280-da1e-11e9-81fd-b5f6e9c26344.png)

Here is the code that I have used

```
dTrack <- DataTrack(SPAST_GR, name = "Beta")
plotTracks(dTrack, groups = rownames(dTrack@data),
           type = c("p"), legend=TRUE, ylim=c(0,2), background.title="darkgrey", fontcolor = "black", col=c(iPSC_ClusterColors$color,ClusterColors$color), fontsize=15, cex = 3)
```

I would appreciate any advice you have on how to fix this.

**Comment by drneavin** [comment]
I figured out the problem was something to do with the groupnames so converting them to a factor before running help.

Here's the updated code:
```
plotTracks(dTrack, groups = factor(rownames(dTrack@data), levels = rownames(dTrack@data)),
           type = c("p"), legend=TRUE, ylim=c(0,2), background.title="darkgrey", fontcolor = "black", col=c(iPSC_ClusterColors$color,rev(ClusterColors$color)), fontsize=15, cex = 3)
```

**Comment by ivanek** [comment]
Hi @drneavin,
I believe, I fixed that issue in the meantime, should work also for character vectors (in version 1.28.3, or in 1.29.3 in devel).
