### ISSUE TITLE
Change transcriptAnnotation parameter for TxDb object

### ISSUE THREAD

**Issue by obenno** [ivanek/Gviz#11]
Hi,

Thanks for the wonderful package.
May I ask when using TxDb object (constructed by GTF/GFF file), how could we set transcriptAnnotation parameter for display?

Thanks.
oben

**Comment by ivanek** [comment]
Hi @obenno, 

Thanks, I am happy you like it. 

You need to use `transcriptAnnotation` argument, for example `transcriptAnnotation="symbol"`.

BTW. This type of question should be asked at Bioc Support forum. 

Best
Robert

**Comment by obenno** [comment]
Hi @ivanek ,

Thanks.
I read the documents and it seems this option does not work with default made TxDb object.
Could you add some examples about using GFF/GTF made TxDb as `GeneRegionTrack` input and parameter tunings in Gviz user guide if possible? I'm working on non-model organisms and have to build database on my own, I know it's better to read GenomicRegion document first, but a few examples would be appreciate and save a lot of time.

Bests,
oben

**Comment by ivanek** [comment]
Could you provide a reproducible example on this issue?

**Comment by obenno** [comment]
Hi @ivanek ,

I attache an example file for test, the code I used is :
```
library(Gviz)
library(GenomicFeatures)
newTxDb <- makeTxDbFromGFF("example.gtf.txt", format="gtf")
gTrack <- GeneRegionTrack(newTxDb, transcriptAnnotation="symbol")
plotTracks(gTrack, chr="Chr04", from=128, to=5304, extend.left=1000, extend.right=1000)
```
May I ask what keys were used to recognized as transcriptAnnotation? I could add them manually to my GTF file. Btw, the gtf file was generated by assembly software stringtie/cufflink. Thanks.

Best,
oben
[example.gtf.txt](https://github.com/ivanek/Gviz/files/3633892/example.gtf.txt)
