### ISSUE TITLE
Recent update to Gviz inverts colors in CAGEfightR

### ISSUE THREAD

**Issue by MalteThodberg** [ivanek/Gviz#12]
Thanks for developing a great package!

I'm developing the CAGEfightR package which provides many functions for interfacing with Gviz.

It seems a recent upgrade to Gviz made some changes to how colors are ordered, causing the CAGEfightR minus/plus strand coloring to swap.

Can you provide some insight into what was changed in Gviz regarding this?

**Comment by ivanek** [comment]
Hi @MalteThodberg,

I am sorry about that. There was an issue with color ordering before. So now `Gviz` keeps the order of provided groups and colours. The safest option is to provide the grouping as factor (you can specify the preferred order of levels) and colours (ordered according to the levels). Hope that helps.
