### ISSUE TITLE
White line overlaps axis in DataTrack

### ISSUE THREAD

**Issue by dhspence** [ivanek/Gviz#17]
Hi,

Thank you for maintaining this package. I find it very useful.

I notice the following issue when plotting multiple tracks on top of each other. There is a white line that covers the lowest axis label, see attached screenshot:

<img width="138" alt="Screen Shot 2019-12-04 at 1 48 25 PM" src="https://user-images.githubusercontent.com/4720638/70175690-ce4bba00-169c-11ea-8862-c5998727daff.png">

Is there a parameter that can be altered to make this transparent? Or eliminate it? Please advise.

If possible, it would also be nice to be able to customize the axis more, like specify the exact values and not have it choose them automatically (so one can just plot the min and max values, for example).

Thanks,

Dave

**Comment by ivanek** [comment]
Hi @dhspence,
Thanks for reporting it.  Could you please provide me a reproducible example? I will help me to debug the issue. 
Best
Robert

**Comment by ivanek** [comment]
- No feedback on the white line. 

- I added a new parameter `yTicksAt` to devel version of `Gviz` 1.31.1 which allows you to specify the position of y-axis tick-marks.

Closing this issue.
