### ISSUE TITLE
Issue in .barsAndLabels()

### ISSUE THREAD

**Issue by TobiTekath** [ivanek/Gviz#19]
Hi,
thanks for this wonderful package.

I stumbled upon a quite rare issue, for which I unfortunately can not provide an reproducible example. But I tracked the error down quite a bit, so I hope this already helps:

In 

https://github.com/ivanek/Gviz/blob/33370fb5a3a243e9fa3165b64fdade85cf9318b4/R/Gviz-methods.R#L1779-L1785

it is possible for _cx_ and _cy_ to have a different length (depending on what _indx_ returns).
This leads to an error in 

https://github.com/ivanek/Gviz/blob/33370fb5a3a243e9fa3165b64fdade85cf9318b4/R/Gviz-methods.R#L1795

```
Error in data.frame(txt = labs, x = cx, y = cy, stringsAsFactors = FALSE) : 
  arguments imply differing number of rows: #length(cx), #length(cy)
```

I did not take the time to fully track down what exactly is happening in this function, but one workaround for the above error would be to just add an `cx <- cx[indx]` to assure the same lengths for the vectors.
The same holds true for the "below" case.

Thanks in advance.

Best,
Tobias

**Comment by ivanek** [comment]
Hi @TobiTekath,

I have checked the code and removed the `restrict`-ion and subsetting. It was only applied to "above" and "below" cases, but it was not applied to to "left" and "right" case. The fix will be in version 1.31.1 devel and I will also try to push it back to release.

Best, Robert
