### ISSUE TITLE
Rasterize datatrack layer

### ISSUE THREAD

**Issue by ParsaAkbari** [ivanek/Gviz#2]
Any chance we can rasterize the datatrack layer? I'm saving the output image as SVG and file sizes get quite large due to a large degree of overlap on the datatrack layers.

**Comment by ivanek** [comment]
Hi @ParsaAkbari, currently I do not have any plan for that, but sounds like an interesting idea. Maybe for autumn 2019 release?

**Comment by ParsaAkbari** [comment]
I agree it should be included in a release at some point. I don't really have time implement this myself at the moment as I am currently writing my PhD thesis :'(
