### ISSUE TITLE
Alignments track for chimeric reads

### ISSUE THREAD

**Issue by aadamk** [ivanek/Gviz#20]
Hello,
Is it possible to generate an alignments track showing a pileup and coverage of chimeric reads?  In my case, I have aligned to a concatenated viral+hg19 reference fasta to identify viral integration sites. I was hoping to generate a pileup image of split reads spanning a breakpoint, similar to the output of 
```
plotTracks(peakReads, 
              chromosome="chr5", 
              from=135312577, 
              to=135314146, 
              type=c("pileup","coverage")).
```
From the documentation, it does not seem that multiple chromosome and 'from/to' entries are supported - I am looking to pileup chimeric reads across a human chr and 'viral chr' (equivalent to a structural variant), for instance. Is this possible?

**Comment by ivanek** [comment]
Hi @aadamk,
Currently` Gviz` supports only visualization on a single chromosome. 
Best
Robert
