### ISSUE TITLE
Unable to save plot to file

### ISSUE THREAD

**Issue by Adrianzo** [ivanek/Gviz#24]
Is it possible to save the plots using R built-in devices: pdf(), png() ?

So far, I've been using an assigment like `p <- plotTracks(atrack)`. But that stills brings the plot on the screen (which I is no trouble, a priori)... But when I do `print(p)` I get text on console:

```
$CpG
AnnotationTrack 'CpG'
| genome: hg19
| active chromosome: chr7
| annotation features: 10

$titles
An object of class "ImageMap"
Slot "coords":
    x1 y1      x2  y2
CpG  6  6 39.5622 667

Slot "tags":
$title
  CpG 
"CpG" 
```

Other libraries (like `ggplot2`) print the actual plot to the active device (by default, the screen. That enables you to get a PDF file simply:

```r
pdf("myPlot.pdf")
print(plot)
dev.off()
```

But this of course is not the case with Gviz plots. How can I achieve such behaviour? Thanks in advance.

**Comment by Adrianzo** [comment]
FYI/Update : I'm clearly having problems with my faculty's proxy. That may offer another explanation to the unusable PDF files I'm getting.I'll retry now using my 3G plan through the phone mobile hotspot.

**Comment by ivanek** [comment]
You do not need to do it the ggplot2' way. You can simply print plots to PDF (assuming there is `atrack` object in the workspace:
```
pdf("myPlot.pdf")
plotTracks(atrack)
dev.off()
```

**Comment by VitorAguiar** [comment]
Hi, what if I do want to assign the plot to a variable? Is it possible?
