### ISSUE TITLE
groups only works in alphabetical order

### ISSUE THREAD

**Issue by mjko1210** [ivanek/Gviz#26]
Hi,

From your example,

data(twoGroups)
dTrack <- DataTrack(twoGroups, name = "uniform")
plotTracks(dTrack, groups=rep(c("control", "treated"), each=3), type=c("a", "p", "confint"))

I realized that no matter how I define the group ordering, it always sort in alphabetical order.

For example, when I replot but with the labels renamed:
plotTracks(dTrack, groups=rep(c("2control","1treated"), each=3), type=c("a", "p", "confint"))

[test.pdf](https://github.com/ivanek/Gviz/files/4301200/test.pdf)

This can be an issue when my data columns are not sorted in alphabetical order.

Thanks,
MJ

**Comment by ivanek** [comment]
Hi @mjko1210,

You need to provide the grouping as a `factor` with defined levels:

```
plotTracks(dTrack, groups=factor(rep(c("2control","1treated"), each=3), 
                                 levels=c("2control", "1treated")),
           type=c("a", "p", "confint"))
```

The sorting is only done when grouping variable is a `character` vector. Otherwise the order of levels is respected.

Best
Robert
