### ISSUE TITLE
Representing SV arcs

### ISSUE THREAD

**Issue by mjko1210** [ivanek/Gviz#27]
Hi,

I have list of SV breaks points, for example

SV.id | chromosome_1 | start_1 | chromosome_2 | start_2
1 | chr1 | 2688849 | chr1 | 2746318
2 | chr1 | 146316299 | chr1 | 149363109
3 | chr1 | 169254858 | chr1 | 16927779

I want to represent breakpoints as arcs connecting each start site.

I've tried to combine datatrack and alignment track to represent this.

Here is my code:

dat = cna.dat  #logR copy number
dat.gr <- as(dat, "GRanges")
dtrack <- DataTrack(dat.gr, genome="hg38", type=c("p"),chromosome="chr1", name = "Copy Number")

sv = read.csv('SV_test.txt',sep='\t')
sv.gr <- as(sv, "GRanges")
alTrack <- AlignmentsTrack(sv.gr)

pdf('sv_test.pdf')
plotTracks(trackList=c(dtrack, alTrack), from=from, to=to, chromosome="chr1", type=c("p","sashimi"))
dev.off()

And sv.gr looks like this
> sv.gr
GRanges object with 1 range and 2 metadata columns:
      seqnames              ranges strand |  strand1  strand2
         <Rle>           <IRanges>  <Rle> | <factor> <factor>
  [1]     chr1 203598556-207630962      * |        +        -

It generated plot as below:

<img width="700" alt="Screen Shot 2020-03-09 at 9 34 23 AM" src="https://user-images.githubusercontent.com/9116362/76243930-5d192700-61f6-11ea-857c-118352848050.png">

I want the arc to be curved line instead of flat one.

Your comments would be greatly appreciated!

Thanks,
MJ

**Comment by ivanek** [comment]
Hi @mjko1210,

maybe you can check the `GenomicInteractions` [vignette](http://www.bioconductor.org/packages/release/bioc/vignettes/GenomicInteractions/inst/doc/hic_vignette.html). The `Gviz` package itself does not currently support that. There is only support for gapped alignments, so called `sashimi` plot.

Best
Robert
