### ISSUE TITLE
Collapse multiple transcripts per gene from geneRegionTrack

### ISSUE THREAD

**Issue by mjko1210** [ivanek/Gviz#28]
Hi,

I'm wondering if there is any way to collapse multiple transcripts (under same gene, MLH1 here) into one.

<img width="959" alt="Screen Shot 2020-03-16 at 10 29 43 PM" src="https://user-images.githubusercontent.com/9116362/76824923-cf30d380-67d5-11ea-803a-332533b63c12.png">

_collapseTranscripts="longest"_ works great for same transcript ID. However, when the same gene has multiple unique transcripts, the plot shows as above. I've tried to use ncbiRefSeqSelect from UcscTrack  so that each gene can show one major transcript, however, it doesn't cover whole genes. 

I'm currently using following settings for gene region track.

grtrack <- GeneRegionTrack(ucscGenes.gr, genome = "hg38", chromosome = chr, name = "UCSC Genes", background.title="brown", shape="arrow", min.width=4, min.height=5)
plotTracks(grtrack, chromosome=chr, from=from, to=to, collapse=T, transcriptAnnotation = 'symbol', collapseTranscripts="longest")

Thanks in advance,
MJ

**Comment by ivanek** [comment]
HI @mjko1210,

Could you let me know, how did you created `ucscGenes.gr` and why were you not using `UcscTrack` directly?

Thanks, Robert

**Comment by mjko1210** [comment]
Hi @ivanek ,

I created gene region track using UcscTrack as below:
```
ucscGenes <- UcscTrack(genome="hg38", table="ncbiRefSeqCurated", track = 'NCBI RefSeq', trackType="GeneRegionTrack",
	                              chromosome=chr, rstarts = "exonStarts", rends = "exonEnds",
	                               gene = "name", symbol = 'name', transcript = "name",
	                               strand = "strand", stacking = 'squish', showID = T, geneSymbol = T, from=from, to=to)
ucscGenes.gr <- ranges(ucscGenes)
mcols(ucscGenes.gr)$symbol <- mapIds(org.Hs.eg.db, gsub("\\.[1-9]$", "", mcols(ucscGenes.gr)$symbol), "SYMBOL","REFSEQ")
```
Thanks!

**Comment by ivanek** [comment]
Hi @mjko1210,

This is not an issue of `Gviz`. You would need to read the [table specification](https://genome-euro.ucsc.edu/cgi-bin/hgTables?db=hg38&hgta_group=genes&hgta_track=refSeqComposite&hgta_table=ncbiRefSeqCurated&hgta_doSchema=describe+table+schema) of the table at UCSC Genome Browser more carefully. By setting `symbol` and `gene` to "name2" you would achieve what you want I guess...

```
library(Gviz)
library(org.Hs.eg.db)

chr <- "chr3"
afrom <- 35985001
ato <- 38059000


ucscGenes <- UcscTrack(genome="hg38", table="ncbiRefSeqCurated", 
                       track = 'NCBI RefSeq', trackType="GeneRegionTrack",
                       chromosome=chr, rstarts = "exonStarts", rends = "exonEnds",
                       gene = "name2", symbol = 'name2', transcript = "name",
                       strand = "strand", stacking = 'squish', showID = TRUE, 
                       geneSymbol = TRUE, from=afrom, to=ato,
                       name = "UCSC Genes", background.title="brown", 
                       shape="arrow", min.width=4, min.height=5)


plotTracks(ucscGenes, chromosome=chr, from=afrom, to=ato, collapse=TRUE, 
           transcriptAnnotation = 'symbol', collapseTranscripts="longest")
```

I am closing this issue.

Best, Robert

**Comment by mjko1210** [comment]
Thanks @ivanek .  This works great!
