### ISSUE TITLE
GeneRegionTrack does not show gene structure

### ISSUE THREAD

**Issue by Zepeng-Mu** [ivanek/Gviz#31]
Hi, I am trying to draw a gene annotation track with different isoforms using the following code:
```
axisTrack <- GenomeAxisTrack()
geneTrack <- GeneRegionTrack(
  range = "gencode.v19.annotation.gff3",
  genome = "hg19",
  chromosome = "chr15",
  start = 27e6,
  end = 30e6
)

plotTracks(list(axisTrack, geneTrack),
           genome = "hg19",
           from = 27e6,
           to = 28e6,
           chromosome = "chr15",
           transcriptAnnotation = "symbol")
```

The reference file is a GFF3 file downloaded from GENCODE website. However, the resulting figure does not show the gene structure (intron/exon). I am wondering what could be wrong and how I can fix it. Thansk

[![Output](https://i.postimg.cc/QMvN4qjd/Screen-Shot-2020-05-14-at-11-15-04.png)](https://postimg.cc/8FBVsMF2)

**Comment by ivanek** [comment]
Hi @Zepeng-Mu,

The reason is, that the imported GFF file (actually the resulting `GeneRegonTrack`) also contains "transcript" features.  If you remove them, the exon-intron structure is correctly plotted. You can also remove "start_codon" and "stop_codon" features.

```
library(Gviz)

axisTrack <- GenomeAxisTrack()
geneTrack <- GeneRegionTrack(
  range = "gencode.v19.annotation.gff3",
  genome = "hg19",
  chromosome = "chr15",
  start = 27e6,
  end = 30e6
)

ranges(geneTrack)$feature <- as.character(ranges(geneTrack)$feature)
# ranges(geneTrack) <- ranges(geneTrack)[!ranges(geneTrack)$feature %in% c("start_codon", "stop_codon ","stop_codon_redefined_as_selenocysteine", "transcript")]
ranges(geneTrack) <- ranges(geneTrack)[ranges(geneTrack)$feature!="transcript"]

plotTracks(list(axisTrack, geneTrack),
           genome = "hg19",
           from = 27e6,
           to = 28e6,
           chromosome = "chr15",
           transcriptAnnotation = "symbol")
```

Another option might be to create a `TxDb` out of the GFF file and use it to build the GeneRegionTrack. Then it  works straight away.

```
library(GenomicFeatures)
library(Gviz)

txdb <- makeTxDbFromGFF("gencode.v19.annotation.gff3")

geneTrack <- GeneRegionTrack(
  range = txdb,
  genome = "hg19",
  chromosome = "chr15",
  start = 27e6,
  end = 30e6
)

plotTracks(list(axisTrack, geneTrack),
           genome = "hg19",
           from = 27e6,
           to = 28e6,
           chromosome = "chr15",
           transcriptAnnotation = "symbol")
```

Best, Robert

**Comment by Zepeng-Mu** [comment]
Thanks!

**Comment by Zepeng-Mu** [comment]
Hi, just as a quick feedback, the second way with `TxDb` I cannot change `transcriptAnnotation = "symbol"`. It is always transcript. But this works with the first way.

**Comment by ivanek** [comment]
This only reflects the data stored in `TxDb` but could be easily changed later in resulting `GeneRegionTrack`:

```
symbol(geneTrack) <- mapIds(org.Hs.eg.db, 
                            keys=sub("\\.\\d+$", "", gene(geneTrack)), 
                            keytype="ENSEMBL", column="SYMBOL")
symbol(geneTrack) <- ifelse(is.na(symbol(geneTrack)), gene(geneTrack), symbol(geneTrack))
```
