### ISSUE TITLE
Unified line width for sashimi plot?

### ISSUE THREAD

**Issue by Zepeng-Mu** [ivanek/Gviz#32]
Hi, thanks for the great package. This is one of the very few tools that meet our need for Sashimi plot. I am wondering whether there is a way to set a unified linewidth range for more than one tracks. Right now different tracks have their different ranges of linewidths. This difference clearly represented in the y-axis. But I hope to make comparisons among samples (tracks) by just looking at the line width without the need to read the axis. I think that would make the difference among samples visually clearer.
Thanks

**Comment by ivanek** [comment]
Hi, 
This is currently not implemented but I can imagine that something similar to `transform` argument of the coverage could also do the job here. I will look at it.

**Comment by ivanek** [comment]
As i wrote, it is not yet implemented.

**Comment by ivanek** [comment]
Hi,
I added `sashimiTransformation` argument  to `AlignmentsTrack`, which works similarly to `transformation` and also expects single argument function. If  only `transfromation` is provided, the same function is applied to coverage and to sashimi score.

Available in version 1.33.1.
