### ISSUE TITLE
How to assign different colours to dots depending on another column

### ISSUE THREAD

**Issue by apfuentes** [ivanek/Gviz#33]
Hi @ivanek,
Thanks so much for developing such wonderful package.

I wonder if there is an option in Gviz to assign different colours to dots depending on another column with factor levels, something similar to what can be accomplished with the scale_color_manual() function of ggplot.

I am trying to create a data track that shows a dot plot like this:
![exampleplot](https://user-images.githubusercontent.com/19496177/88153585-e52c2600-cc05-11ea-8d7f-2e25b3ca2c3c.png)

I generated the example plot with ggplot:
```
library(ggplot2)
p <- ggplot(ChiSqr_subset, aes(x = end, y = log10P)) + 
  geom_point(aes(colour = as.factor(effect))) +
  scale_color_manual(name = "Effect categories",
                     values = c('missense_variant' = '#e31a1c',
                                'synonymous_variant' = '#1f78b4',
                                '5_prime_UTR_variant' = '#feb24c', 
                                '3_prime_UTR_variant' = '#feb24c',
                                'upstream_gene_variant' = '#feb24c',
                                'downstream_gene_variant' = '#feb24c',
                                'intron_variant' = 'gray',
                                'intergenic_region' = 'gray'#,
                                #NA = 'black'
                                ),
                     breaks = effect_order,
                     labels = c('Coding non-synonymous', 'Coding synonymous', '5-prime UTR', 
                                '3-prime UTR', '5kb upstream', '5kb downstream', 
                                'Intron', 'Intergenic')) +
  labs(x = "SNP", y = "-log10(P-value)") +
  theme_classic() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
p
```
The input data frame `ChiSqr_subset` looks like:
```
  chromosome start  end log10P            effect
1       chr1   757  757              3.838054 intergenic_region
2       chr1  1383 1383              1.789974 intergenic_region
3       chr1  1403 1403              1.409600 intergenic_region
4       chr1  2684 2684              1.506558 5_prime_UTR_variant
5       chr1  2685 2685              1.491539 intergenic_region
6       chr1  2689 2689              1.212418 synonymous_variant
```
Note that the column "effect" is of type character and the categories repeat.

To try to generate this plot using Gviz, I followed these steps:
- converted the input data frame into GRanges using the makeGRangesFromDataFrame() function:
```
ChiSqr_GR <- makeGRangesFromDataFrame(ChiSqr_subset,
                                      keep.extra.columns = TRUE)
```
- converted the resulting Granges object to a Gviz data track using the DataTrack() constructor:
```
dTrack_ChiSqr <- DataTrack(range = ChiSqr_GR,
                        name = '-log10(P-value)',
                        cex = 0.5,
                        #chromosome = Chr, from = Start, to = End,
                        #cex.axis = 1,
                        #col.axis = 'black', col.title = 'black', background.title = 'white', background.panel = 'white',
                        options(ucscChromosomeNames = FALSE)
)
```
The "effect" column is being discarded by the dataTrack constructor because it is not numeric:
```
Warning message:
In .prepareDtData(data, len = length(range)) :
  The following non-numeric data column has been dropped: effect
```
Then I tried to add the categorical groupings to the data track by setting `groups = `  to the vector equivalent to the `effect` column from the original data frame `ChiSqr_subset`, but it does not work:
```
plotTracks(dTrack, groups = factor(ChiSqr_subset$effect, levels = effect_order), type = c("p"), legend = TRUE)
```
The vector given as "levels" was:
```
effect_order <- c('missense_variant', 'synonymous_variant', '5_prime_UTR_variant', 
                  '3_prime_UTR_variant', 'upstream_gene_variant', 'downstream_gene_variant', 
                  'intron_variant', 'intergenic_region')
```
Get this error message: 
```
Error in .local(GdObject, ...) : 
  'groups' must be a vector of similar length as the number of rows in the data matrix (1)
```
But confirmed the length is the same between the groups vector and the dataTrack object:
```
> length(dTrack_ChiSqr)
[1] 47049
> length(ChiSqr_subset$effect)
[1] 47049
```
Any recommendation on how to solve this problem will be greatly appreciated.

Thanks,
Angela

**Comment by ivanek** [comment]
Hi @apfuentes,

I guess you found the way how to do it, essentially the data for different groups must be in separate columns (`mcols`).

Best
Robert

**Comment by apfuentes** [comment]
Yes, I figured it out, thanks!

**Comment by aselewa** [comment]
Hi, can you share the code you used to generate this plot? I am trying to do something similar. Thanks
