### ISSUE TITLE
Reverse-strand alignment sorted by end position in AlignmentsTrack pileup

### ISSUE THREAD

**Issue by opplatek** [ivanek/Gviz#34]
Hi Robert, I would like to use Gviz to visualize long-read data alignments. My main issue is a sort/order of reads mapped to the reverse strand. The pileups are by default sorted by start coordinates which makes it difficult to read. Would it be possible to sort the alignments by the end position instead? Maybe only when reverseStrand=T. I believe it would make sense for short-read visualization as well. Another option would be to allow a custom order for the alignments. 

Forward strand read alignment looks nice (example [here](https://www.dropbox.com/s/3ktyrh4kfic78fz/lr-forward.png?dl=0)) and I would like the reverse strand read alignment to look the same (right now I have [this](https://www.dropbox.com/s/coe8ooz0rbpe2kn/lr-reverse.png?dl=0)).  The _style_ I would like to have is the top left corner to the bottom right corner diagonal in the forward strand alignments.

**Comment by ivanek** [comment]
Hi @opplatek,

There is no way how to define the order of the alignments, `Gviz` tries to order them efficiently for plotting. Have you also tried to set `reverseStacking=TRUE` ? It will reverse the order of the reads for plotting (from bottom to top).

**Comment by opplatek** [comment]
Hi @ivanek,

Yes, I have tried the  `reverseStacking=TRUE`, didn't help. So it's really not possible to change the sort from start position to end position? I understand Gviz tries to fit the alignments to a single view but they are obviously sorted by the start position. 

If it's not possible I will try to find some other way how to make the visualization look nice and you can close this thread. Thanks.
