### ISSUE TITLE
Error in .local(.Object, ...) : Failed to obtain 'hguid' cookie

### ISSUE THREAD

**Issue by mjko1210** [ivanek/Gviz#35]
Hi,

I'm getting following errors frequently when I submitted several jobs with slurm on the server.

Error in .local(.Object, ...) : Failed to obtain 'hguid' cookie
Calls: IdeogramTrack ... browserSession -> new -> initialize -> initialize -> .local

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS/LAPACK: /app/software/OpenBLAS/0.3.1-GCC-7.3.0-2.30/lib/libopenblas_haswellp-r0.3.1.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C


```
Seems like I'm getting this error when it fetches the data from UCSC, is there way to avoid this issues? For example, if it's possible to download ideogram information in advance and load the data instead.

I also found this `options(Gviz.ucscUrl="http://genome-euro.ucsc.edu/cgi-bin/".`  from document.  what's the default ucscUrl that's been used for standard run?

Thanks!

**Comment by ivanek** [comment]
Hi, 

You can fetch the information from UCSC only once and store the `.ucscCache` into a file. 

```
IdeogramTrack(chromosome=seqnames("chr1", genome="mm10")
saveRDS(Gviz:::.ucscCache, file=sprintf("ucscCache_%s.rds", "mm10"))
```
Afterwards simply load it as you need. 

```
.ucscCache <- readRDS(sprintf("ucscCache.%s.rds", "mm10"))
assignInNamespace(".ucscCache", .ucscCache, ns="Gviz")
```

Just keep in mind that you need to initiate it for every genome version from UCSC you are planning to use.

**Comment by ivanek** [comment]
Closing, no feedback.

**Comment by ytwangZero** [comment]
Hi,
I meet the same problem. Would you like to share how you solved it?
thanks!
Best regards
