### ISSUE TITLE
individual base colors in alignment tracks

### ISSUE THREAD

**Issue by rrazaghi** [ivanek/Gviz#38]
Hi,

I was wondering if there's a way that specific bases in the alignment track can be colored differently on a single read level according to a user-defined tag in the bam. This is especially helpful in visualizing single long read methylation data.

Thanks!

**Comment by ivanek** [comment]
Hi @rrazaghi,

Can you elaborate on it a bit please? Could you also share an example of data?

**Comment by ivanek** [comment]
No feedback, closing.
