### ISSUE TITLE
BiomartGeneRegionTrack and depreciated dplyr functions

### ISSUE THREAD

**Issue by 14stutzmanav** [ivanek/Gviz#43]
Hello,

I am having a problem when I run BiomartGeneRegionTrack(). When I try to run the command, I have an error that reads,
> `select_()` was deprecated in dplyr 0.7.0.
> Please use `select()` instead.`filter_()` was deprecated in dplyr 0.7.0.
> Please use `filter()` instead.
> See vignette('programming') for more helpError in UseMethod("filter_") : 
>   no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"

Is there any way to fix this problem?

Thank you so much!

**Comment by ivanek** [comment]
Hi @14stutzmanav,

There is not a lot information in your post (missing `sessionInfo()`and reproducible piece of code leading to the error). 
However I would expect that there is a conflict between `tidyverse` and `Bioc` worlds. 

I would recommend you, that you load first `dplyr` (or `tidyverse`) and only afterwards load `Bioc` libraries (like `Gviz`).

Hope that helps, best, Robert

**Comment by lorbaer** [comment]
Hi,
I can confirm this problem. select_ and filter_ are deprecated and are going to show warnings/errors with "older" versions.
However loading FIRST dplyr/tidyverse and later on Gviz is going to work.

I had the chance to test it on  a fresh installed R + packages. Warning/Error is not showing any more.

[session.txt](https://github.com/ivanek/Gviz/files/6388920/session.txt)

best
