### ISSUE TITLE
display annotations in separate lines

### ISSUE THREAD

**Issue by mjko1210** [ivanek/Gviz#44]
Hi, 
Is there way to separate peaks in separate lines? (met H3k27ac annotation track in this example)[
<img width="780" alt="Screen Shot 2021-04-01 at 12 53 46 PM" src="https://user-images.githubusercontent.com/9116362/113347251-bc5a4580-92e9-11eb-8bfa-bfa951fd9d0b.png">
](url)

I wish I can separate individual peaks in separate lines so that I can read individual peak's name.

Thanks!

**Comment by ivanek** [comment]
Hi @mjko1210,

Without any code and any example data it is hard for me to help you. I can only point you in the direction of using `group` and `groupAnnotation="group"` and stacking="squish", please check the Gviz vignette for `AnnotationTrack`.

Best, Robert

**Comment by ivanek** [comment]
no feedback, closing
