### ISSUE TITLE
y ticks not showing correct values for custmized aggregation function 

### ISSUE THREAD

**Issue by ruqianl** [ivanek/Gviz#46]
Hi @ivanek ,

Thanks for the great package!

I'm trying to display a SNP density track with log10 transformed values for 'hist' type DataTracks, the code snipet was used: 
``` 
snp_track <- DataTrack( GRanges(seqnames = chrom,
                                IRanges(start=snp_anno$POS,
                                        wsidth = 1,
                                        genome = "mm10")),
                        name = "SNPs denstiy",
                        data = rep(1,nrow(snp_anno)),
                        window = nwindow,
                        aggregation  = function(x) { log10(sum(x)+1)},
                        type=plot_type)
```
It gives the correct histogram shape but the scale and ticks on the y axis are off:
![image](https://user-images.githubusercontent.com/12887308/117256306-dd382c80-ae8d-11eb-894c-ed53514d8dad.png)

The scale on y should be from [0,4] but it is all under 1 as shown.

If comparing to using the "sum" as the aggregation function:
![image](https://user-images.githubusercontent.com/12887308/117256348-ecb77580-ae8d-11eb-960b-0611725bca42.png)

Any idea about how to fix this?

Thanks,
Ruqian

**Comment by ivanek** [comment]
Hi @ruqianl,
Sorry for the delay, I only had time to fix it now. 
Best
Robert
