### ISSUE TITLE
Alignments error

### ISSUE THREAD

**Issue by BioEpi** [ivanek/Gviz#51]
Hello,
    I ran Gviz successfully. But today when I ran `Alignments` function, I got the following error:
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'sort': different row counts implied by arguments
here is the command:
_AlignmentsTrack(thisrangs,cigar=thisrange.cigar,isPaired=FALSE,name=hic_name,type="sashimi", lwd.sashimiMax=3)_

**Comment by ivanek** [comment]
Hi @BioEpi,
could you share with me part of the data in order to reproduce the error?
Thanks, Robert

**Comment by ivanek** [comment]
Closing no response.
