### ISSUE TITLE
Inconsistent Indel annotation with IGV

### ISSUE THREAD

**Issue by ctl43** [ivanek/Gviz#58]
Hi Gviz developers, thanks for creating this powerful genome visualisation package.
I used Gviz to visualise indels, however, I found that the annotation is not consistent with IGV (see figure); Gviz extended one more base to the right.

I wonder whether this is a bug or not.
Here is my code
`read_track <- AlignmentsTrack(range = bam, stacking = "full", showIndels = TRUE, isPaired=TRUE)`
`seq_track <- SequenceTrack(genome)`
`plotTracks(list(seq_track, read_track), chromosome = chr, from = start, to = end)`
![gviz_igv](https://user-images.githubusercontent.com/33325636/140264777-abab63b2-656b-43d0-ad1d-dcf629de71ca.png)

Thanks!

**Comment by ivanek** [comment]
Hi @ctl43, 
Thanks for reporting. I fixed it in devel (>=  1.39.2) and release (>=  1.38.1) versions.
Best, Robert
