### ISSUE TITLE
Scaling of arrowBar

### ISSUE THREAD

**Issue by TobiTekath** [ivanek/Gviz#6]
Hi @ivanek, 

I really like the Gviz package because of its flexibility. But I stumbled upon a minor problem: 

When i am creating high resolution images of my transcript models, the arrow-bar connecting the different exons does not seem to scale at all. So at high resolutions the arrows are nearly invisible.
I found the default values for _W_, _D_ and _min.height_ in _.arrowBar()_ to be the culprits.

Would it be possible to let the arrows automatically scale with resolution? Or at least to expose the values (_W_, _D_ and _min.height_) in the GeneRegionTrack-class so they can easily be adjusted if needed?

Thanks in advance.

___________________________________________________________________________

Here is how it looks with default values:
![bad](https://user-images.githubusercontent.com/42060788/61057921-8464ed80-a3f6-11e9-9464-bd6ce0829f77.png)

Here is how it looks with adjusted values:
![better](https://user-images.githubusercontent.com/42060788/61057940-9181dc80-a3f6-11e9-9afa-2d5fd0d586ce.png)

**Comment by ivanek** [comment]
I exposed two parameters: `arrowFeatherWidth` (W) and `arrowFeatherDistance` (D), `min.height` was already available. So far only in the GitHub version. I will later push it also to devel version in Bioc.

example setting:
```
displayPars(grtrack)$arrowFeatherWidth <- 15 
```

**Comment by TobiTekath** [comment]
Thanks alot, I will try it out soon.
