### ISSUE TITLE
How to plot only the gene ( not the transcripts) using GeneRegionTrack?

### ISSUE THREAD

**Issue by Sneha-bioinfo** [ivanek/Gviz#66]
I'm trying to create a probe map showing probes mapped to the IKZF1 gene. Using the GeneRegion Track, I'm trying to plot just the gene with it's exons ( at the DNA level).... before even splicing occurs. However the final plot show's all the 22 transcripts of the gene. Is there any way to plot just the gene?
These are the commands i used:-
chr <- "chr7"

TxDb<-TxDb.Hsapiens.UCSC.hg38.knownGene

grtrack <- GeneRegionTrack(TxDb, chromosome="chr", start = 50304124, end = 50405101, shape= "arrow")
This is the output i created :-

![IMG_20220820_153310](https://user-images.githubusercontent.com/88312813/185752427-edf511a2-89e4-4170-82f2-b2f241cb4a95.jpg)

I'm trying to create something like this ( the image is  from a publication)
![IMG_20220820_153336](https://user-images.githubusercontent.com/88312813/185752526-41da8dce-eb67-4d38-8955-7fcabec34322.jpg)

**Comment by ivanek** [comment]
Hi @Sneha-bioinfo, 
This is not an issue for GitHub. This should be discussed in the Bioc Mailing list.
However this particular question is also mentioned in the [Gviz vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/Gviz/inst/doc/Gviz.html#45_GeneRegionTrack):

....
Or we can plot the union of all the exons in some sort of meta-transcript.

```
plotTracks(grtrack, collapseTranscripts = "meta", shape = "arrow", 
           transcriptAnnotation = "symbol")
```

....

Best, Robert

**Comment by Sneha-bioinfo** [comment]
Noted, Thank you!

Regards,
Sneha
