### ISSUE TITLE
BiomartGeneRegionTrack generated an object contained wrong end information

### ISSUE THREAD

**Issue by powerhorse1986** [ivanek/Gviz#70]
Hi,

Our group is using Gvic to plot methylation status of a specific gene. I have to say it's a really powerful tool! However, when I was plotting the plot for gene MDM2, I found that the plot was way too wide. Then I dived into the code, and I found out that the end information provided by the BiomartGeneRegionTrack object was wrong. I used the following code to generate the object and to get the end information:

`bm <- useEnsembl(host = "https://grch37.ensembl.org", 
                 biomart = "ENSEMBL_MART_ENSEMBL",
                 dataset = "hsapiens_gene_ensembl")
biomTrack <- BiomartGeneRegionTrack(genome = genome, 
                                    name = "MDM2", 
                                    symbol = "MDM2", 
                                    biomart = mart )
biomTrack@end`

biomTrack@end returned me the value 69365350, which is different from the value 69239214 according to ensembl for GRCh37.
Would you please help fix this? Thank you!

Li Ma

**Comment by ivanek** [comment]
Hi @powerhorse1986,

First of all your code is not reproducible.

The generated object contains also genes in the neighborhood. If you look specifically for gene _MDM2_ then you can see that the gene coordinates  stored in `BiomartGeneRegionTrack` match those  provided by ensembl:

```
library(biomaRt)
library(Gviz)

bm <- useEnsembl(host = "https://grch37.ensembl.org",  biomart = "ENSEMBL_MART_ENSEMBL", dataset = "hsapiens_gene_ensembl") 
biomTrack <- BiomartGeneRegionTrack(genome = "grch37",  name = "MDM2",  symbol = "MDM2",  biomart = bm ) 

range(ranges(biomTrack)[ranges(biomTrack)$symbol=="MDM2"])
```

```
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]    chr12 69201956-69239214      +
  -------
  seqinfo: 1 sequence from grch37 genome; no seqlengths
```
