### ISSUE TITLE
Incorrect labeling dot plot using DataTrack

### ISSUE THREAD

**Issue by powerhorse1986** [ivanek/Gviz#74]
Hi,

I am using Gviz to build a plot for viewing methylation status of different gene regions. It's really an awesome package! 

However, I added a DataTrack into the plot and I found that the legend of the group was wrong.

The data is
 dataTrack@data
        [,1]       [,2]       [,3]       [,4]       [,5]       [,6]      [,7]       [,8]      [,9]
Tu 0.2307692 0.13519164 0.04970326 0.04463875 0.02643071 0.03699422 0.0657277 0.09742501 0.4438959
DN 0.2597865 0.08716707 0.03458878 0.01438323 0.01761006 0.02673435 0.0106562 0.02276532 0.0660737

In the attached plot, blue points represent the Tu sample, pink points represent the DN sample. However, according to the data, blue points should be DN sample and pink points should be Tu sample.

![image](https://user-images.githubusercontent.com/47227800/219500731-dd5656af-2f40-4834-b937-99b16f2b2e2d.png)

**Comment by ivanek** [comment]
Hi @powerhorse1986,

I fixed the issue, I will push the fix to release version too. In the meantime, you can specify the `groups` as a factor with defined order of levels:

```
plotTracks(dataTrack, groups=factor(c("Tu", "Dn"), levels=c("Tu", "Dn")))
```
