### ISSUE TITLE
  There doesn't seem to be any cytoband data available for genome 'hg38' at UCSC or the service is temporarily down. Trying to fetch the chromosome length data.

### ISSUE THREAD

**Issue by ChristianRohde** [ivanek/Gviz#78]
Hi,

this command _IdeogramTrack(chromosome = "chr19", genome = "hg38", showBandId = TRUE)_ used to work, but at the moment I get the following error:

Error in value[[3L]](cond) : 
  There doesn't seem to be any chromosome length data available for genome 'hg38' at UCSC or the service is temporarily down.
In addition: Warning message:
In value[[3L]](cond) :
  There doesn't seem to be any cytoband data available for genome 'hg38' at UCSC or the service is temporarily down. Trying to fetch the chromosome length data.

Can you confirm that this is a problem on the UCSC side? Is there anything I can do about this issue?

Best,
Christian

**Comment by ivanek** [comment]
Hi @ChristianRohde,
I believe this might be error caused by not having access to UCSC. It works fine for me.
Best, Robert

**Comment by ChristianRohde** [comment]
Thank you for your answer: you are right, I realize now that I have this problem with Gviz_1.38.4 running under R version 4.1.2 only. I can confirm that it works fine with R version 4.2.2 and Gviz_1.42.1. I am sorry that I did not test it on a different system before reporting this issue.

Best,
Christian
