### ISSUE TITLE
Incorrect plotting of a sequence track with index (.fa.idx) 

### ISSUE THREAD

**Issue by AlexandreBeaudoin** [ivanek/Gviz#8]
When running this code:
```
refseq <- Gviz::SequenceTrack("sequence.fa")
Gviz::plotTracks(
  trackList=c(refseq),
  from=200,
  to=600,
  chromosome="chr1")
```
When sequence.fa does not have an index, refseq is of class "SequenceDNAStringSetTrack" and everything displays correctly.

However if I add an index:
```
samtools faidx sequence.fa
```
refseq is now a "ReferenceSequenceTrack" class and the track is not displayed correctly.  Depending on the 'from' and 'to' nothing or an incorrect snippet is displayed.

Since the index works correctly in other programs, my guess is that there's some problem with "ReferenceSequenceTrack" but I'm unsure how to proceed.

Alex

**Comment by ivanek** [comment]
Hi @AlexandreBeaudoin ,

Thanks for reporting this bug, I fixed it in both devel  (1.29.1) and release (1.28.1) versions. 
Please keep in mind, that for `ReferenceSequenceTrack` you need to specify the `chromosome`.

Best, Robert
